const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const stub=new Proxy(()=>{},{get:()=>stub});
const chrome=Object.create(stub);
chrome.tabs={get:async()=>({url:'https://www.91porn.com/view_video.php?viewkey=1507572698'}),onRemoved:stub};
chrome.scripting={executeScript:async({func})=>[{result:'https://cdn.example/video.mp4'}]};
const ctx=vm.createContext({chrome,URL,navigator:{userAgent:'test'}});
vm.runInContext(fs.readFileSync('browser_extension/background.js','utf8'),ctx);
(async()=>{
 ctx.probeApp=async()=>({ok:false,error:'unsupported'});
 const u='https://www.91porn.com/view_video.php?viewkey=1507572698';
 const r=await ctx.probeMedia(u,{},1);
 assert.equal(r.formats[0].format_id,'browser:direct');
 let sent;ctx.sendToApp=async(url,opts)=>{sent={url,opts};return {ok:true}};
 await ctx.downloadMedia({kind:'page',url:u,title:'测试视频'},{best:true},1);
 assert.equal(sent.url,'https://cdn.example/video.mp4');
 assert.equal(sent.opts.media_type,'file');
 ctx.browserYouTube=async()=>({formats:[{height:360,url:'https://x.googlevideo.com/videoplayback',ext:'mp4'}]});
 ctx.probeApp=async()=>({ok:true,formats:[{height:720,format_id:'298+140',label:'720p'}]});
 const yt='https://www.youtube.com/watch?v=2PHqki02vUI';
 const formats=await ctx.probeMedia(yt,{},1);
 assert.equal(formats.formats[0].height,720);
 await ctx.downloadMedia({kind:'page',url:yt,title:'测试视频'},{best:true},1);
 assert.equal(sent.url,yt);assert.equal(sent.opts.media_type,'page');assert.equal(sent.opts.best,true);
 const miss='https://missav.ai/fc2-ppv-4979251';
 ctx.recommendedDetected=()=>({url:'https://cdn.example/master.m3u8',kind:'hls',title:'测试影片',size:0});
 ctx.probeApp=async(url)=>url===miss?{ok:false,error:'403'}:{ok:true,variants:[{height:720,label:'720p'}]};
 const mr=await ctx.probeMedia(miss,{},1);
 assert.equal(mr.formats[0].format_id,'browser:detected');
 assert.equal(mr.formats[1].height,720);
 await ctx.downloadMedia({kind:'page',url:miss,title:'测试影片'},{best:true},1);
 assert.equal(sent.url,'https://cdn.example/master.m3u8');
 assert.equal(sent.opts.media_type,'hls');
 const xin='https://www.xinpianchang.com/a13802723';
 ctx.recommendedDetected=()=>({url:'https://cdn.example/movie.mp4',kind:'file',title:'测试短片',size:42_000_000});
 ctx.probeApp=async()=>({ok:false,error:'403'});
 const xr=await ctx.probeMedia(xin,{},1);
 assert.equal(xr.formats[0].format_id,'browser:detected');
 await ctx.downloadMedia({kind:'page',url:xin,title:'测试短片'},{best:true},1);
 assert.equal(sent.url,'https://cdn.example/movie.mp4');
 console.log('PASS: YouTube, 91porn, MissAV and 新片场 browser routes');
})().catch(e=>{console.error(e);process.exitCode=1});

